version: '3.8'

services:
  api:
    build: .
    container_name: ai_service_api
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/ai_agent
    volumes:
      - .:/app
    depends_on:
      - db
      - mock_api

  mock_api:
    build: 
      context: ./mock_api
      dockerfile: Dockerfile
    container_name: mock_external_api
    ports:
      - "8001:8001"
    volumes:
      - ./mock_api:/app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
